[tool.poetry]
name = "netdantic"
version = "0.1.0"
description = ""
authors = ["Brandon Spendlove <br@ndonspendlove.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
